clone:
  clone:
    image: plugins/git
    recursive: true

pipeline:
  semantic-release:
    image: python:2.7-alpine
    commands:
      - npm install --save-dev semantic-release
      - npx semantic-release