clone:
  clone:
    image: plugins/git
    recursive: true

pipeline:
  semantic-release:
    image: tarampampam/node:10.10-alpine
    secrets: [gh_token]
    commands:
      - npm install semantic-release
      - npx semantic-release