clone:
  clone:
    image: plugins/git
    recursive: true

pipeline:
  semantic-release:
    image: node:8-alpine
    commands:
      - npm install --save-dev semantic-release
      - npm install @semantic-release/git -Dt
      - git --version
      - npx semantic-release